require sklearn <0.24.0 due to unpickle error
With scikit-learn 0.24.0 it is failing with:
ModuleNotFoundError: No module named 'sklearn.feature_extraction.dict_vectorizer'